# This file contains design-specific Leda rules for DW_apb_i2c component

#LMD: Leda rule check for BCM file
#LJ: Leda rule check for BCM's disabled, those can only be fixed by BCM RnD
 rule_deselect -all -file ../src/DW_apb_i2c_bcm06.v 

#LMD: Leda rule check for BCM file
#LJ: Leda rule check for BCM's disabled, those can only be fixed by BCM RnD
 rule_deselect -all -file ../src/DW_apb_i2c_bcm21.v 

#LMD: Leda rule check for BCM file
#LJ: Leda rule check for BCM's disabled, those can only be fixed by BCM RnD
 rule_deselect -all -file ../src/DW_apb_i2c_bcm57.v 


#LMD: Nested ifs. Consider using case or casex statement instead
#LJ: We use case statement if more than two conditions are present.
#LJ: LUIS will remove this Rule in the upcoming Leda rules release
rule_deselect -rule W526

#LMD: Use Vector operations on arrays rather than for loops
#LJ: Loop statements are used for reability purpose.
#LJ: LUIS will remove this Rule in the upcoming Leda rules release
rule_deselect -rule G_5214_2

#LMD: Do not declare `define inside module.
#LJ: This violation is present in the BCM module 'DWbb_bcm21.v'.
#    waving it until the BCM RnD group fixed it.
rule_deselect -rule B_3440 

#LMD: Possible loss of carry/borrow in addition/subtraction
#LJ: All arithmetic additions and substractions are listed and analyzed.
#    Planned to write assertions locally to not violate the possibility of losing carry/borrow
rule_deselect -rule W484

# LMD: Change on net has no effect on any of the output
# LJ:  Leda version 2013.03-02 flags false violations and those are fixed in latest version of leda 
rule_deselect -rule NTL_CON32

#LMD: Nets or cell pins should not be tied to logic 0 / logic 1
#LJ: Leda rule flagging on different file which is misleading.
#    STAR 9000723726 is filed to resolve this issue
 rule_deselect -all -file  ../src/DW_apb_i2c-undef.v 

#LMD: Non driving internal net
#LJ: Leda rule flagging false violations in master fsm
 rule_deselect -all -file  ../src/DW_apb_i2c_mstfsm.v 


# Deselect CDC rulset
# Analysis done through Spyglass
rule_deselect -ruleset CDC -policy DESIGN

#LMD: Divergence found in clock domain crossing path
#LJ: Enabled only for control paths and disabled the data paths.
#    Data signals are a qualified with the valid synchronized control signal.
rule_set_parameter -rule NTL_CDC03 -parameter CHECK_DATA_PATHS -value {0}

#LMD: CDC control signal must not be part of a BUS
#LJ: Enabled only for Synchronized control paths
#    Data signals are a qualified with the valid synchronized control signal.
rule_set_parameter -rule NTL_CDC09 -parameter SHOW_ONLY_CONTROL_PATHS -value 1

#LMD: Control and Data Signals of a MUX (Logic) Synchronizer must be Stable Enough (Property Generated)
#LJ: The assertion properties are generated by the Leda too to test in Magellan tool.
#    Currently not planned to test them.
rule_deselect -rule NTL_CDC14

#reuse-pragma endSub cdcRules




