###################################################################

# Created by write_sdc on Sat Nov 28 20:52:04 2015

###################################################################
set sdc_version 2.0

set_units -time ns -resistance 1.000000e+04kOhm -capacitance 1.000000e-04pF -voltage V -current uA
set_operating_conditions nom_pvt -library lsi_10k
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports PRESETn_presetn]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[31]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[30]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[29]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[28]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[27]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[26]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[25]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[24]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[23]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[22]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[21]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[20]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[19]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[18]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[17]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[16]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[15]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[14]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[13]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[12]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[11]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[10]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[9]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[8]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[7]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[6]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[5]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[4]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[3]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[2]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[1]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_haddr[0]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hburst[2]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hburst[1]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hburst[0]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports ex_i_ahb_AHB_Master_hbusreq]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports ex_i_ahb_AHB_Master_hlock]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hprot[3]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hprot[2]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hprot[1]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hprot[0]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hsize[2]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hsize[1]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hsize[0]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_htrans[1]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_htrans[0]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[31]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[30]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[29]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[28]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[27]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[26]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[25]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[24]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[23]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[22]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[21]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[20]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[19]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[18]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[17]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[16]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[15]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[14]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[13]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[12]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[11]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[10]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[9]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[8]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[7]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[6]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[5]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[4]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[3]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[2]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[1]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Master_hwdata[0]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports ex_i_ahb_AHB_Master_hwrite]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[31]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[30]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[29]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[28]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[27]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[26]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[25]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[24]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[23]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[22]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[21]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[20]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[19]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[18]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[17]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[16]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[15]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[14]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[13]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[12]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[11]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[10]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[9]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[8]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[7]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[6]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[5]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[4]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[3]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[2]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[1]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hrdata[0]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports ex_i_ahb_AHB_Slave_hready_resp]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hresp[1]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports {ex_i_ahb_AHB_Slave_hresp[0]}]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports i_ahb_pause]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports i_apb_pclk_en]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports i_i2c_ic_clk_in_a]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports i_i2c_ic_data_in_a]
set_driving_cell -lib_cell FJK1 -library lsi_10k -pin Q -no_design_rule [get_ports i_i2c_ic_rst_n]
set_port_fanout_number 3 [get_ports ex_i_ahb_AHB_Master_hgrant]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[31]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[30]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[29]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[28]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[27]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[26]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[25]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[24]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[23]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[22]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[21]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[20]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[19]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[18]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[17]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[16]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[15]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[14]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[13]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[12]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[11]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[10]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[9]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[8]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[7]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[6]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[5]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[4]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[3]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[2]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[1]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[0]}]
set_port_fanout_number 6 [get_ports ex_i_ahb_AHB_Master_hready]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hresp[1]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Master_hresp[0]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[31]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[30]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[29]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[28]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[27]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[26]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[25]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[24]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[23]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[22]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[21]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[20]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[19]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[18]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[17]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[16]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[15]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[14]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[13]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[12]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[11]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[10]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[9]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[8]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[7]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[6]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[5]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[4]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[3]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[2]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[1]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[0]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hburst[2]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hburst[1]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hburst[0]}]
set_port_fanout_number 3 [get_ports ex_i_ahb_AHB_Slave_hmastlock]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hprot[3]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hprot[2]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hprot[1]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hprot[0]}]
set_port_fanout_number 6 [get_ports ex_i_ahb_AHB_Slave_hready]
set_port_fanout_number 3 [get_ports ex_i_ahb_AHB_Slave_hsel]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hsize[2]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hsize[1]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hsize[0]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_htrans[1]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_htrans[0]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[31]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[30]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[29]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[28]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[27]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[26]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[25]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[24]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[23]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[22]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[21]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[20]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[19]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[18]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[17]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[16]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[15]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[14]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[13]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[12]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[11]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[10]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[9]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[8]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[7]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[6]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[5]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[4]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[3]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[2]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[1]}]
set_port_fanout_number 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[0]}]
set_port_fanout_number 6 [get_ports ex_i_ahb_AHB_Slave_hwrite]
set_port_fanout_number 3 [get_ports i_ahb_ahbarbint]
set_port_fanout_number 3 [get_ports {i_ahb_hmaster_data[3]}]
set_port_fanout_number 3 [get_ports {i_ahb_hmaster_data[2]}]
set_port_fanout_number 3 [get_ports {i_ahb_hmaster_data[1]}]
set_port_fanout_number 3 [get_ports {i_ahb_hmaster_data[0]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[31]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[30]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[29]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[28]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[27]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[26]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[25]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[24]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[23]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[22]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[21]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[20]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[19]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[18]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[17]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[16]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[15]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[14]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[13]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[12]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[11]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[10]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[9]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[8]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[7]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[6]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[5]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[4]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[3]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[2]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[1]}]
set_port_fanout_number 6 [get_ports {i_ahb_hrdata_s0[0]}]
set_port_fanout_number 6 [get_ports i_ahb_hready_resp_s0]
set_port_fanout_number 6 [get_ports {i_ahb_hresp_s0[1]}]
set_port_fanout_number 6 [get_ports {i_ahb_hresp_s0[0]}]
set_port_fanout_number 3 [get_ports i_ahb_hsel_s0]
set_port_fanout_number 3 [get_ports i_i2c_debug_addr]
set_port_fanout_number 3 [get_ports i_i2c_debug_addr_10bit]
set_port_fanout_number 3 [get_ports i_i2c_debug_data]
set_port_fanout_number 3 [get_ports i_i2c_debug_hs]
set_port_fanout_number 3 [get_ports i_i2c_debug_master_act]
set_port_fanout_number 3 [get_ports {i_i2c_debug_mst_cstate[4]}]
set_port_fanout_number 3 [get_ports {i_i2c_debug_mst_cstate[3]}]
set_port_fanout_number 3 [get_ports {i_i2c_debug_mst_cstate[2]}]
set_port_fanout_number 3 [get_ports {i_i2c_debug_mst_cstate[1]}]
set_port_fanout_number 3 [get_ports {i_i2c_debug_mst_cstate[0]}]
set_port_fanout_number 3 [get_ports i_i2c_debug_p_gen]
set_port_fanout_number 3 [get_ports i_i2c_debug_rd]
set_port_fanout_number 3 [get_ports i_i2c_debug_s_gen]
set_port_fanout_number 3 [get_ports i_i2c_debug_slave_act]
set_port_fanout_number 3 [get_ports {i_i2c_debug_slv_cstate[3]}]
set_port_fanout_number 3 [get_ports {i_i2c_debug_slv_cstate[2]}]
set_port_fanout_number 3 [get_ports {i_i2c_debug_slv_cstate[1]}]
set_port_fanout_number 3 [get_ports {i_i2c_debug_slv_cstate[0]}]
set_port_fanout_number 3 [get_ports i_i2c_debug_wr]
set_port_fanout_number 3 [get_ports i_i2c_ic_activity_intr]
set_port_fanout_number 3 [get_ports i_i2c_ic_clk_oe]
set_port_fanout_number 3 [get_ports i_i2c_ic_data_oe]
set_port_fanout_number 3 [get_ports i_i2c_ic_en]
set_port_fanout_number 3 [get_ports i_i2c_ic_gen_call_intr]
set_port_fanout_number 3 [get_ports i_i2c_ic_rd_req_intr]
set_port_fanout_number 3 [get_ports i_i2c_ic_rx_done_intr]
set_port_fanout_number 3 [get_ports i_i2c_ic_rx_full_intr]
set_port_fanout_number 3 [get_ports i_i2c_ic_rx_over_intr]
set_port_fanout_number 3 [get_ports i_i2c_ic_rx_under_intr]
set_port_fanout_number 3 [get_ports i_i2c_ic_start_det_intr]
set_port_fanout_number 3 [get_ports i_i2c_ic_stop_det_intr]
set_port_fanout_number 3 [get_ports i_i2c_ic_tx_abrt_intr]
set_port_fanout_number 3 [get_ports i_i2c_ic_tx_empty_intr]
set_port_fanout_number 3 [get_ports i_i2c_ic_tx_over_intr]
set_load -pin_load 3 [get_ports ex_i_ahb_AHB_Master_hgrant]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[31]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[30]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[29]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[28]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[27]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[26]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[25]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[24]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[23]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[22]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[21]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[20]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[19]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[18]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[17]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[16]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[15]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[14]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[13]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[12]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[11]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[10]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[9]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[8]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[7]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[6]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[5]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[4]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[3]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[2]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[1]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hrdata[0]}]
set_load -pin_load 6 [get_ports ex_i_ahb_AHB_Master_hready]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hresp[1]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Master_hresp[0]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[31]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[30]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[29]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[28]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[27]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[26]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[25]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[24]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[23]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[22]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[21]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[20]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[19]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[18]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[17]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[16]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[15]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[14]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[13]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[12]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[11]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[10]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[9]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[8]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[7]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[6]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[5]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[4]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[3]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[2]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[1]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_haddr[0]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hburst[2]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hburst[1]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hburst[0]}]
set_load -pin_load 3 [get_ports ex_i_ahb_AHB_Slave_hmastlock]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hprot[3]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hprot[2]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hprot[1]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hprot[0]}]
set_load -pin_load 6 [get_ports ex_i_ahb_AHB_Slave_hready]
set_load -pin_load 3 [get_ports ex_i_ahb_AHB_Slave_hsel]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hsize[2]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hsize[1]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hsize[0]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_htrans[1]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_htrans[0]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[31]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[30]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[29]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[28]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[27]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[26]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[25]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[24]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[23]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[22]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[21]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[20]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[19]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[18]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[17]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[16]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[15]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[14]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[13]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[12]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[11]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[10]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[9]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[8]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[7]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[6]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[5]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[4]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[3]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[2]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[1]}]
set_load -pin_load 6 [get_ports {ex_i_ahb_AHB_Slave_hwdata[0]}]
set_load -pin_load 6 [get_ports ex_i_ahb_AHB_Slave_hwrite]
set_load -pin_load 3 [get_ports i_ahb_ahbarbint]
set_load -pin_load 3 [get_ports {i_ahb_hmaster_data[3]}]
set_load -pin_load 3 [get_ports {i_ahb_hmaster_data[2]}]
set_load -pin_load 3 [get_ports {i_ahb_hmaster_data[1]}]
set_load -pin_load 3 [get_ports {i_ahb_hmaster_data[0]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[31]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[30]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[29]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[28]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[27]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[26]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[25]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[24]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[23]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[22]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[21]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[20]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[19]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[18]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[17]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[16]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[15]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[14]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[13]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[12]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[11]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[10]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[9]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[8]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[7]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[6]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[5]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[4]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[3]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[2]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[1]}]
set_load -pin_load 6 [get_ports {i_ahb_hrdata_s0[0]}]
set_load -pin_load 6 [get_ports i_ahb_hready_resp_s0]
set_load -pin_load 6 [get_ports {i_ahb_hresp_s0[1]}]
set_load -pin_load 6 [get_ports {i_ahb_hresp_s0[0]}]
set_load -pin_load 3 [get_ports i_ahb_hsel_s0]
set_load -pin_load 3 [get_ports i_i2c_debug_addr]
set_load -pin_load 3 [get_ports i_i2c_debug_addr_10bit]
set_load -pin_load 3 [get_ports i_i2c_debug_data]
set_load -pin_load 3 [get_ports i_i2c_debug_hs]
set_load -pin_load 3 [get_ports i_i2c_debug_master_act]
set_load -pin_load 3 [get_ports {i_i2c_debug_mst_cstate[4]}]
set_load -pin_load 3 [get_ports {i_i2c_debug_mst_cstate[3]}]
set_load -pin_load 3 [get_ports {i_i2c_debug_mst_cstate[2]}]
set_load -pin_load 3 [get_ports {i_i2c_debug_mst_cstate[1]}]
set_load -pin_load 3 [get_ports {i_i2c_debug_mst_cstate[0]}]
set_load -pin_load 3 [get_ports i_i2c_debug_p_gen]
set_load -pin_load 3 [get_ports i_i2c_debug_rd]
set_load -pin_load 3 [get_ports i_i2c_debug_s_gen]
set_load -pin_load 3 [get_ports i_i2c_debug_slave_act]
set_load -pin_load 3 [get_ports {i_i2c_debug_slv_cstate[3]}]
set_load -pin_load 3 [get_ports {i_i2c_debug_slv_cstate[2]}]
set_load -pin_load 3 [get_ports {i_i2c_debug_slv_cstate[1]}]
set_load -pin_load 3 [get_ports {i_i2c_debug_slv_cstate[0]}]
set_load -pin_load 3 [get_ports i_i2c_debug_wr]
set_load -pin_load 3 [get_ports i_i2c_ic_activity_intr]
set_load -pin_load 3 [get_ports i_i2c_ic_clk_oe]
set_load -pin_load 3 [get_ports i_i2c_ic_data_oe]
set_load -pin_load 3 [get_ports i_i2c_ic_en]
set_load -pin_load 3 [get_ports i_i2c_ic_gen_call_intr]
set_load -pin_load 3 [get_ports i_i2c_ic_rd_req_intr]
set_load -pin_load 3 [get_ports i_i2c_ic_rx_done_intr]
set_load -pin_load 3 [get_ports i_i2c_ic_rx_full_intr]
set_load -pin_load 3 [get_ports i_i2c_ic_rx_over_intr]
set_load -pin_load 3 [get_ports i_i2c_ic_rx_under_intr]
set_load -pin_load 3 [get_ports i_i2c_ic_start_det_intr]
set_load -pin_load 3 [get_ports i_i2c_ic_stop_det_intr]
set_load -pin_load 3 [get_ports i_i2c_ic_tx_abrt_intr]
set_load -pin_load 3 [get_ports i_i2c_ic_tx_empty_intr]
set_load -pin_load 3 [get_ports i_i2c_ic_tx_over_intr]
create_clock [get_ports HCLK_hclk]  -period 6  -waveform {0 3}
set_clock_latency 0  [get_clocks HCLK_hclk]
set_clock_latency -source 0  [get_clocks HCLK_hclk]
set_clock_uncertainty 0  [get_clocks HCLK_hclk]
create_clock [get_ports PCLK_pclk]  -period 6  -waveform {0 3}
set_clock_latency 0  [get_clocks PCLK_pclk]
set_clock_latency -source 0  [get_clocks PCLK_pclk]
set_clock_uncertainty 0  [get_clocks PCLK_pclk]
create_clock [get_ports i_i2c_ic_clk]  -period 6  -waveform {0 3}
set_clock_latency 0  [get_clocks i_i2c_ic_clk]
set_clock_latency -source 0  [get_clocks i_i2c_ic_clk]
set_clock_uncertainty 0  [get_clocks i_i2c_ic_clk]
group_path -name FEEDTHROUGH  -from [list [get_ports HRESETn_hresetn] [get_ports PRESETn_presetn] [get_ports {ex_i_ahb_AHB_Master_haddr[31]}] [get_ports {ex_i_ahb_AHB_Master_haddr[30]}] [get_ports {ex_i_ahb_AHB_Master_haddr[29]}] [get_ports {ex_i_ahb_AHB_Master_haddr[28]}] [get_ports {ex_i_ahb_AHB_Master_haddr[27]}] [get_ports {ex_i_ahb_AHB_Master_haddr[26]}] [get_ports {ex_i_ahb_AHB_Master_haddr[25]}] [get_ports {ex_i_ahb_AHB_Master_haddr[24]}] [get_ports {ex_i_ahb_AHB_Master_haddr[23]}] [get_ports {ex_i_ahb_AHB_Master_haddr[22]}] [get_ports {ex_i_ahb_AHB_Master_haddr[21]}] [get_ports {ex_i_ahb_AHB_Master_haddr[20]}] [get_ports {ex_i_ahb_AHB_Master_haddr[19]}] [get_ports {ex_i_ahb_AHB_Master_haddr[18]}] [get_ports {ex_i_ahb_AHB_Master_haddr[17]}] [get_ports {ex_i_ahb_AHB_Master_haddr[16]}] [get_ports {ex_i_ahb_AHB_Master_haddr[15]}] [get_ports {ex_i_ahb_AHB_Master_haddr[14]}] [get_ports {ex_i_ahb_AHB_Master_haddr[13]}] [get_ports {ex_i_ahb_AHB_Master_haddr[12]}] [get_ports {ex_i_ahb_AHB_Master_haddr[11]}] [get_ports {ex_i_ahb_AHB_Master_haddr[10]}] [get_ports {ex_i_ahb_AHB_Master_haddr[9]}] [get_ports {ex_i_ahb_AHB_Master_haddr[8]}] [get_ports {ex_i_ahb_AHB_Master_haddr[7]}] [get_ports {ex_i_ahb_AHB_Master_haddr[6]}] [get_ports {ex_i_ahb_AHB_Master_haddr[5]}] [get_ports {ex_i_ahb_AHB_Master_haddr[4]}] [get_ports {ex_i_ahb_AHB_Master_haddr[3]}] [get_ports {ex_i_ahb_AHB_Master_haddr[2]}] [get_ports {ex_i_ahb_AHB_Master_haddr[1]}] [get_ports {ex_i_ahb_AHB_Master_haddr[0]}] [get_ports {ex_i_ahb_AHB_Master_hburst[2]}] [get_ports {ex_i_ahb_AHB_Master_hburst[1]}] [get_ports {ex_i_ahb_AHB_Master_hburst[0]}] [get_ports ex_i_ahb_AHB_Master_hbusreq] [get_ports ex_i_ahb_AHB_Master_hlock] [get_ports {ex_i_ahb_AHB_Master_hprot[3]}] [get_ports {ex_i_ahb_AHB_Master_hprot[2]}] [get_ports {ex_i_ahb_AHB_Master_hprot[1]}] [get_ports {ex_i_ahb_AHB_Master_hprot[0]}] [get_ports {ex_i_ahb_AHB_Master_hsize[2]}] [get_ports {ex_i_ahb_AHB_Master_hsize[1]}] [get_ports {ex_i_ahb_AHB_Master_hsize[0]}] [get_ports {ex_i_ahb_AHB_Master_htrans[1]}] [get_ports {ex_i_ahb_AHB_Master_htrans[0]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[31]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[30]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[29]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[28]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[27]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[26]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[25]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[24]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[23]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[22]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[21]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[20]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[19]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[18]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[17]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[16]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[15]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[14]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[13]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[12]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[11]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[10]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[9]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[8]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[7]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[6]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[5]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[4]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[3]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[2]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[1]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[0]}] [get_ports ex_i_ahb_AHB_Master_hwrite] [get_ports {ex_i_ahb_AHB_Slave_hrdata[31]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[30]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[29]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[28]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[27]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[26]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[25]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[24]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[23]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[22]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[21]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[20]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[19]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[18]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[17]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[16]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[15]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[14]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[13]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[12]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[11]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[10]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[9]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[8]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[7]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[6]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[5]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[4]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[3]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[2]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[1]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[0]}] [get_ports ex_i_ahb_AHB_Slave_hready_resp] [get_ports {ex_i_ahb_AHB_Slave_hresp[1]}] [get_ports {ex_i_ahb_AHB_Slave_hresp[0]}] [get_ports i_ahb_pause] [get_ports i_apb_pclk_en] [get_ports i_i2c_ic_clk_in_a] [get_ports i_i2c_ic_data_in_a] [get_ports i_i2c_ic_rst_n]]  -to [list [get_ports ex_i_ahb_AHB_Master_hgrant] [get_ports {ex_i_ahb_AHB_Master_hrdata[31]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[30]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[29]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[28]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[27]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[26]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[25]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[24]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[23]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[22]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[21]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[20]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[19]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[18]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[17]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[16]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[15]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[14]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[13]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[12]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[11]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[10]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[9]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[8]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[7]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[6]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[5]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[4]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[3]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[2]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[1]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[0]}] [get_ports ex_i_ahb_AHB_Master_hready] [get_ports {ex_i_ahb_AHB_Master_hresp[1]}] [get_ports {ex_i_ahb_AHB_Master_hresp[0]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[31]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[30]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[29]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[28]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[27]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[26]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[25]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[24]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[23]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[22]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[21]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[20]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[19]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[18]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[17]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[16]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[15]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[14]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[13]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[12]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[11]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[10]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[9]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[8]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[7]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[6]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[5]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[4]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[3]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[2]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[1]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[0]}] [get_ports {ex_i_ahb_AHB_Slave_hburst[2]}] [get_ports {ex_i_ahb_AHB_Slave_hburst[1]}] [get_ports {ex_i_ahb_AHB_Slave_hburst[0]}] [get_ports ex_i_ahb_AHB_Slave_hmastlock] [get_ports {ex_i_ahb_AHB_Slave_hprot[3]}] [get_ports {ex_i_ahb_AHB_Slave_hprot[2]}] [get_ports {ex_i_ahb_AHB_Slave_hprot[1]}] [get_ports {ex_i_ahb_AHB_Slave_hprot[0]}] [get_ports ex_i_ahb_AHB_Slave_hready] [get_ports ex_i_ahb_AHB_Slave_hsel] [get_ports {ex_i_ahb_AHB_Slave_hsize[2]}] [get_ports {ex_i_ahb_AHB_Slave_hsize[1]}] [get_ports {ex_i_ahb_AHB_Slave_hsize[0]}] [get_ports {ex_i_ahb_AHB_Slave_htrans[1]}] [get_ports {ex_i_ahb_AHB_Slave_htrans[0]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[31]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[30]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[29]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[28]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[27]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[26]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[25]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[24]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[23]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[22]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[21]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[20]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[19]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[18]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[17]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[16]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[15]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[14]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[13]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[12]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[11]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[10]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[9]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[8]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[7]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[6]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[5]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[4]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[3]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[2]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[1]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[0]}] [get_ports ex_i_ahb_AHB_Slave_hwrite] [get_ports i_ahb_ahbarbint] [get_ports {i_ahb_hmaster_data[3]}] [get_ports {i_ahb_hmaster_data[2]}] [get_ports {i_ahb_hmaster_data[1]}] [get_ports {i_ahb_hmaster_data[0]}] [get_ports {i_ahb_hrdata_s0[31]}] [get_ports {i_ahb_hrdata_s0[30]}] [get_ports {i_ahb_hrdata_s0[29]}] [get_ports {i_ahb_hrdata_s0[28]}] [get_ports {i_ahb_hrdata_s0[27]}] [get_ports {i_ahb_hrdata_s0[26]}] [get_ports {i_ahb_hrdata_s0[25]}] [get_ports {i_ahb_hrdata_s0[24]}] [get_ports {i_ahb_hrdata_s0[23]}] [get_ports {i_ahb_hrdata_s0[22]}] [get_ports {i_ahb_hrdata_s0[21]}] [get_ports {i_ahb_hrdata_s0[20]}] [get_ports {i_ahb_hrdata_s0[19]}] [get_ports {i_ahb_hrdata_s0[18]}] [get_ports {i_ahb_hrdata_s0[17]}] [get_ports {i_ahb_hrdata_s0[16]}] [get_ports {i_ahb_hrdata_s0[15]}] [get_ports {i_ahb_hrdata_s0[14]}] [get_ports {i_ahb_hrdata_s0[13]}] [get_ports {i_ahb_hrdata_s0[12]}] [get_ports {i_ahb_hrdata_s0[11]}] [get_ports {i_ahb_hrdata_s0[10]}] [get_ports {i_ahb_hrdata_s0[9]}] [get_ports {i_ahb_hrdata_s0[8]}] [get_ports {i_ahb_hrdata_s0[7]}] [get_ports {i_ahb_hrdata_s0[6]}] [get_ports {i_ahb_hrdata_s0[5]}] [get_ports {i_ahb_hrdata_s0[4]}] [get_ports {i_ahb_hrdata_s0[3]}] [get_ports {i_ahb_hrdata_s0[2]}] [get_ports {i_ahb_hrdata_s0[1]}] [get_ports {i_ahb_hrdata_s0[0]}] [get_ports i_ahb_hready_resp_s0] [get_ports {i_ahb_hresp_s0[1]}] [get_ports {i_ahb_hresp_s0[0]}] [get_ports i_ahb_hsel_s0] [get_ports i_i2c_debug_addr] [get_ports i_i2c_debug_addr_10bit] [get_ports i_i2c_debug_data] [get_ports i_i2c_debug_hs] [get_ports i_i2c_debug_master_act] [get_ports {i_i2c_debug_mst_cstate[4]}] [get_ports {i_i2c_debug_mst_cstate[3]}] [get_ports {i_i2c_debug_mst_cstate[2]}] [get_ports {i_i2c_debug_mst_cstate[1]}] [get_ports {i_i2c_debug_mst_cstate[0]}] [get_ports i_i2c_debug_p_gen] [get_ports i_i2c_debug_rd] [get_ports i_i2c_debug_s_gen] [get_ports i_i2c_debug_slave_act] [get_ports {i_i2c_debug_slv_cstate[3]}] [get_ports {i_i2c_debug_slv_cstate[2]}] [get_ports {i_i2c_debug_slv_cstate[1]}] [get_ports {i_i2c_debug_slv_cstate[0]}] [get_ports i_i2c_debug_wr] [get_ports i_i2c_ic_activity_intr] [get_ports i_i2c_ic_clk_oe] [get_ports i_i2c_ic_data_oe] [get_ports i_i2c_ic_en] [get_ports i_i2c_ic_gen_call_intr] [get_ports i_i2c_ic_rd_req_intr] [get_ports i_i2c_ic_rx_done_intr] [get_ports i_i2c_ic_rx_full_intr] [get_ports i_i2c_ic_rx_over_intr] [get_ports i_i2c_ic_rx_under_intr] [get_ports i_i2c_ic_start_det_intr] [get_ports i_i2c_ic_stop_det_intr] [get_ports i_i2c_ic_tx_abrt_intr] [get_ports i_i2c_ic_tx_empty_intr] [get_ports i_i2c_ic_tx_over_intr]]
group_path -name REGIN  -from [list [get_ports HRESETn_hresetn] [get_ports PRESETn_presetn] [get_ports {ex_i_ahb_AHB_Master_haddr[31]}] [get_ports {ex_i_ahb_AHB_Master_haddr[30]}] [get_ports {ex_i_ahb_AHB_Master_haddr[29]}] [get_ports {ex_i_ahb_AHB_Master_haddr[28]}] [get_ports {ex_i_ahb_AHB_Master_haddr[27]}] [get_ports {ex_i_ahb_AHB_Master_haddr[26]}] [get_ports {ex_i_ahb_AHB_Master_haddr[25]}] [get_ports {ex_i_ahb_AHB_Master_haddr[24]}] [get_ports {ex_i_ahb_AHB_Master_haddr[23]}] [get_ports {ex_i_ahb_AHB_Master_haddr[22]}] [get_ports {ex_i_ahb_AHB_Master_haddr[21]}] [get_ports {ex_i_ahb_AHB_Master_haddr[20]}] [get_ports {ex_i_ahb_AHB_Master_haddr[19]}] [get_ports {ex_i_ahb_AHB_Master_haddr[18]}] [get_ports {ex_i_ahb_AHB_Master_haddr[17]}] [get_ports {ex_i_ahb_AHB_Master_haddr[16]}] [get_ports {ex_i_ahb_AHB_Master_haddr[15]}] [get_ports {ex_i_ahb_AHB_Master_haddr[14]}] [get_ports {ex_i_ahb_AHB_Master_haddr[13]}] [get_ports {ex_i_ahb_AHB_Master_haddr[12]}] [get_ports {ex_i_ahb_AHB_Master_haddr[11]}] [get_ports {ex_i_ahb_AHB_Master_haddr[10]}] [get_ports {ex_i_ahb_AHB_Master_haddr[9]}] [get_ports {ex_i_ahb_AHB_Master_haddr[8]}] [get_ports {ex_i_ahb_AHB_Master_haddr[7]}] [get_ports {ex_i_ahb_AHB_Master_haddr[6]}] [get_ports {ex_i_ahb_AHB_Master_haddr[5]}] [get_ports {ex_i_ahb_AHB_Master_haddr[4]}] [get_ports {ex_i_ahb_AHB_Master_haddr[3]}] [get_ports {ex_i_ahb_AHB_Master_haddr[2]}] [get_ports {ex_i_ahb_AHB_Master_haddr[1]}] [get_ports {ex_i_ahb_AHB_Master_haddr[0]}] [get_ports {ex_i_ahb_AHB_Master_hburst[2]}] [get_ports {ex_i_ahb_AHB_Master_hburst[1]}] [get_ports {ex_i_ahb_AHB_Master_hburst[0]}] [get_ports ex_i_ahb_AHB_Master_hbusreq] [get_ports ex_i_ahb_AHB_Master_hlock] [get_ports {ex_i_ahb_AHB_Master_hprot[3]}] [get_ports {ex_i_ahb_AHB_Master_hprot[2]}] [get_ports {ex_i_ahb_AHB_Master_hprot[1]}] [get_ports {ex_i_ahb_AHB_Master_hprot[0]}] [get_ports {ex_i_ahb_AHB_Master_hsize[2]}] [get_ports {ex_i_ahb_AHB_Master_hsize[1]}] [get_ports {ex_i_ahb_AHB_Master_hsize[0]}] [get_ports {ex_i_ahb_AHB_Master_htrans[1]}] [get_ports {ex_i_ahb_AHB_Master_htrans[0]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[31]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[30]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[29]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[28]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[27]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[26]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[25]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[24]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[23]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[22]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[21]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[20]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[19]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[18]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[17]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[16]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[15]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[14]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[13]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[12]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[11]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[10]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[9]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[8]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[7]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[6]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[5]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[4]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[3]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[2]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[1]}] [get_ports {ex_i_ahb_AHB_Master_hwdata[0]}] [get_ports ex_i_ahb_AHB_Master_hwrite] [get_ports {ex_i_ahb_AHB_Slave_hrdata[31]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[30]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[29]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[28]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[27]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[26]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[25]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[24]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[23]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[22]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[21]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[20]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[19]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[18]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[17]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[16]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[15]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[14]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[13]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[12]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[11]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[10]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[9]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[8]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[7]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[6]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[5]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[4]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[3]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[2]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[1]}] [get_ports {ex_i_ahb_AHB_Slave_hrdata[0]}] [get_ports ex_i_ahb_AHB_Slave_hready_resp] [get_ports {ex_i_ahb_AHB_Slave_hresp[1]}] [get_ports {ex_i_ahb_AHB_Slave_hresp[0]}] [get_ports i_ahb_pause] [get_ports i_apb_pclk_en] [get_ports i_i2c_ic_clk_in_a] [get_ports i_i2c_ic_data_in_a] [get_ports i_i2c_ic_rst_n]]
group_path -name REGOUT  -to [list [get_ports ex_i_ahb_AHB_Master_hgrant] [get_ports {ex_i_ahb_AHB_Master_hrdata[31]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[30]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[29]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[28]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[27]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[26]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[25]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[24]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[23]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[22]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[21]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[20]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[19]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[18]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[17]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[16]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[15]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[14]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[13]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[12]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[11]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[10]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[9]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[8]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[7]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[6]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[5]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[4]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[3]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[2]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[1]}] [get_ports {ex_i_ahb_AHB_Master_hrdata[0]}] [get_ports ex_i_ahb_AHB_Master_hready] [get_ports {ex_i_ahb_AHB_Master_hresp[1]}] [get_ports {ex_i_ahb_AHB_Master_hresp[0]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[31]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[30]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[29]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[28]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[27]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[26]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[25]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[24]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[23]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[22]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[21]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[20]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[19]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[18]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[17]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[16]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[15]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[14]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[13]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[12]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[11]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[10]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[9]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[8]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[7]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[6]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[5]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[4]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[3]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[2]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[1]}] [get_ports {ex_i_ahb_AHB_Slave_haddr[0]}] [get_ports {ex_i_ahb_AHB_Slave_hburst[2]}] [get_ports {ex_i_ahb_AHB_Slave_hburst[1]}] [get_ports {ex_i_ahb_AHB_Slave_hburst[0]}] [get_ports ex_i_ahb_AHB_Slave_hmastlock] [get_ports {ex_i_ahb_AHB_Slave_hprot[3]}] [get_ports {ex_i_ahb_AHB_Slave_hprot[2]}] [get_ports {ex_i_ahb_AHB_Slave_hprot[1]}] [get_ports {ex_i_ahb_AHB_Slave_hprot[0]}] [get_ports ex_i_ahb_AHB_Slave_hready] [get_ports ex_i_ahb_AHB_Slave_hsel] [get_ports {ex_i_ahb_AHB_Slave_hsize[2]}] [get_ports {ex_i_ahb_AHB_Slave_hsize[1]}] [get_ports {ex_i_ahb_AHB_Slave_hsize[0]}] [get_ports {ex_i_ahb_AHB_Slave_htrans[1]}] [get_ports {ex_i_ahb_AHB_Slave_htrans[0]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[31]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[30]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[29]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[28]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[27]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[26]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[25]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[24]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[23]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[22]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[21]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[20]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[19]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[18]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[17]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[16]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[15]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[14]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[13]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[12]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[11]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[10]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[9]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[8]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[7]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[6]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[5]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[4]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[3]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[2]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[1]}] [get_ports {ex_i_ahb_AHB_Slave_hwdata[0]}] [get_ports ex_i_ahb_AHB_Slave_hwrite] [get_ports i_ahb_ahbarbint] [get_ports {i_ahb_hmaster_data[3]}] [get_ports {i_ahb_hmaster_data[2]}] [get_ports {i_ahb_hmaster_data[1]}] [get_ports {i_ahb_hmaster_data[0]}] [get_ports {i_ahb_hrdata_s0[31]}] [get_ports {i_ahb_hrdata_s0[30]}] [get_ports {i_ahb_hrdata_s0[29]}] [get_ports {i_ahb_hrdata_s0[28]}] [get_ports {i_ahb_hrdata_s0[27]}] [get_ports {i_ahb_hrdata_s0[26]}] [get_ports {i_ahb_hrdata_s0[25]}] [get_ports {i_ahb_hrdata_s0[24]}] [get_ports {i_ahb_hrdata_s0[23]}] [get_ports {i_ahb_hrdata_s0[22]}] [get_ports {i_ahb_hrdata_s0[21]}] [get_ports {i_ahb_hrdata_s0[20]}] [get_ports {i_ahb_hrdata_s0[19]}] [get_ports {i_ahb_hrdata_s0[18]}] [get_ports {i_ahb_hrdata_s0[17]}] [get_ports {i_ahb_hrdata_s0[16]}] [get_ports {i_ahb_hrdata_s0[15]}] [get_ports {i_ahb_hrdata_s0[14]}] [get_ports {i_ahb_hrdata_s0[13]}] [get_ports {i_ahb_hrdata_s0[12]}] [get_ports {i_ahb_hrdata_s0[11]}] [get_ports {i_ahb_hrdata_s0[10]}] [get_ports {i_ahb_hrdata_s0[9]}] [get_ports {i_ahb_hrdata_s0[8]}] [get_ports {i_ahb_hrdata_s0[7]}] [get_ports {i_ahb_hrdata_s0[6]}] [get_ports {i_ahb_hrdata_s0[5]}] [get_ports {i_ahb_hrdata_s0[4]}] [get_ports {i_ahb_hrdata_s0[3]}] [get_ports {i_ahb_hrdata_s0[2]}] [get_ports {i_ahb_hrdata_s0[1]}] [get_ports {i_ahb_hrdata_s0[0]}] [get_ports i_ahb_hready_resp_s0] [get_ports {i_ahb_hresp_s0[1]}] [get_ports {i_ahb_hresp_s0[0]}] [get_ports i_ahb_hsel_s0] [get_ports i_i2c_debug_addr] [get_ports i_i2c_debug_addr_10bit] [get_ports i_i2c_debug_data] [get_ports i_i2c_debug_hs] [get_ports i_i2c_debug_master_act] [get_ports {i_i2c_debug_mst_cstate[4]}] [get_ports {i_i2c_debug_mst_cstate[3]}] [get_ports {i_i2c_debug_mst_cstate[2]}] [get_ports {i_i2c_debug_mst_cstate[1]}] [get_ports {i_i2c_debug_mst_cstate[0]}] [get_ports i_i2c_debug_p_gen] [get_ports i_i2c_debug_rd] [get_ports i_i2c_debug_s_gen] [get_ports i_i2c_debug_slave_act] [get_ports {i_i2c_debug_slv_cstate[3]}] [get_ports {i_i2c_debug_slv_cstate[2]}] [get_ports {i_i2c_debug_slv_cstate[1]}] [get_ports {i_i2c_debug_slv_cstate[0]}] [get_ports i_i2c_debug_wr] [get_ports i_i2c_ic_activity_intr] [get_ports i_i2c_ic_clk_oe] [get_ports i_i2c_ic_data_oe] [get_ports i_i2c_ic_en] [get_ports i_i2c_ic_gen_call_intr] [get_ports i_i2c_ic_rd_req_intr] [get_ports i_i2c_ic_rx_done_intr] [get_ports i_i2c_ic_rx_full_intr] [get_ports i_i2c_ic_rx_over_intr] [get_ports i_i2c_ic_rx_under_intr] [get_ports i_i2c_ic_start_det_intr] [get_ports i_i2c_ic_stop_det_intr] [get_ports i_i2c_ic_tx_abrt_intr] [get_ports i_i2c_ic_tx_empty_intr] [get_ports i_i2c_ic_tx_over_intr]]
set_false_path   -from [get_clocks PCLK_pclk]  -to [get_clocks i_i2c_ic_clk]
set_false_path   -from [get_clocks i_i2c_ic_clk]  -to [get_clocks PCLK_pclk]
set_input_delay -clock HCLK_hclk  0  [get_ports HRESETn_hresetn]
set_input_delay -clock PCLK_pclk  2.4  [get_ports PRESETn_presetn]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[31]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[30]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[29]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[28]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[27]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[26]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[25]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[24]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[23]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[22]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[21]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[20]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[19]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[18]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[17]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[16]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[15]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[14]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[13]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[12]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[11]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[10]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[9]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[8]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[7]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[6]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[5]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[4]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[3]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[2]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[1]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_haddr[0]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hburst[2]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hburst[1]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hburst[0]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports ex_i_ahb_AHB_Master_hbusreq]
set_input_delay -clock HCLK_hclk  1.2  [get_ports ex_i_ahb_AHB_Master_hlock]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hprot[3]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hprot[2]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hprot[1]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hprot[0]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hsize[2]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hsize[1]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hsize[0]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_htrans[1]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_htrans[0]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[31]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[30]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[29]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[28]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[27]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[26]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[25]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[24]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[23]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[22]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[21]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[20]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[19]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[18]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[17]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[16]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[15]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[14]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[13]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[12]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[11]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[10]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[9]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[8]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[7]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[6]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[5]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[4]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[3]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[2]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[1]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Master_hwdata[0]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports ex_i_ahb_AHB_Master_hwrite]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[31]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[30]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[29]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[28]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[27]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[26]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[25]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[24]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[23]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[22]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[21]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[20]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[19]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[18]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[17]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[16]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[15]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[14]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[13]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[12]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[11]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[10]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[9]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[8]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[7]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[6]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[5]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[4]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[3]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[2]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[1]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hrdata[0]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports ex_i_ahb_AHB_Slave_hready_resp]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hresp[1]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports {ex_i_ahb_AHB_Slave_hresp[0]}]
set_input_delay -clock HCLK_hclk  1.2  [get_ports i_ahb_pause]
set_input_delay -clock HCLK_hclk  3.96  [get_ports i_apb_pclk_en]
set_input_delay -clock i_i2c_ic_clk  2.4  [get_ports i_i2c_ic_clk_in_a]
set_input_delay -clock i_i2c_ic_clk  2.4  [get_ports i_i2c_ic_data_in_a]
set_input_delay -clock i_i2c_ic_clk  2.4  [get_ports i_i2c_ic_rst_n]
set_output_delay -clock HCLK_hclk  1.8  [get_ports ex_i_ahb_AHB_Master_hgrant]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[31]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[30]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[29]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[28]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[27]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[26]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[25]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[24]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[23]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[22]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[21]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[20]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[19]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[18]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[17]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[16]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[15]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[14]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[13]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[12]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[11]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[10]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[9]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[8]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[7]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[6]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[5]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[4]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[3]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[2]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[1]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hrdata[0]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports ex_i_ahb_AHB_Master_hready]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hresp[1]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Master_hresp[0]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[31]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[30]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[29]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[28]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[27]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[26]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[25]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[24]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[23]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[22]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[21]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[20]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[19]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[18]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[17]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[16]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[15]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[14]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[13]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[12]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[11]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[10]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[9]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[8]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[7]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[6]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[5]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[4]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[3]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[2]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[1]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_haddr[0]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hburst[2]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hburst[1]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hburst[0]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports ex_i_ahb_AHB_Slave_hmastlock]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hprot[3]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hprot[2]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hprot[1]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hprot[0]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports ex_i_ahb_AHB_Slave_hready]
set_output_delay -clock HCLK_hclk  1.8  [get_ports ex_i_ahb_AHB_Slave_hsel]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hsize[2]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hsize[1]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hsize[0]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_htrans[1]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_htrans[0]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[31]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[30]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[29]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[28]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[27]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[26]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[25]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[24]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[23]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[22]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[21]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[20]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[19]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[18]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[17]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[16]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[15]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[14]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[13]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[12]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[11]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[10]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[9]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[8]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[7]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[6]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[5]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[4]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[3]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[2]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[1]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {ex_i_ahb_AHB_Slave_hwdata[0]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports ex_i_ahb_AHB_Slave_hwrite]
set_output_delay -clock HCLK_hclk  1.8  [get_ports i_ahb_ahbarbint]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {i_ahb_hmaster_data[3]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {i_ahb_hmaster_data[2]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {i_ahb_hmaster_data[1]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports {i_ahb_hmaster_data[0]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[31]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[30]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[29]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[28]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[27]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[26]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[25]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[24]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[23]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[22]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[21]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[20]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[19]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[18]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[17]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[16]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[15]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[14]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[13]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[12]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[11]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[10]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[9]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[8]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[7]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[6]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[5]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[4]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[3]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[2]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[1]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hrdata_s0[0]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports i_ahb_hready_resp_s0]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hresp_s0[1]}]
set_output_delay -clock HCLK_hclk  4.2  [get_ports {i_ahb_hresp_s0[0]}]
set_output_delay -clock HCLK_hclk  1.8  [get_ports i_ahb_hsel_s0]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports i_i2c_debug_addr]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports i_i2c_debug_addr_10bit]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports i_i2c_debug_data]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports i_i2c_debug_hs]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports i_i2c_debug_master_act]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports {i_i2c_debug_mst_cstate[4]}]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports {i_i2c_debug_mst_cstate[3]}]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports {i_i2c_debug_mst_cstate[2]}]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports {i_i2c_debug_mst_cstate[1]}]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports {i_i2c_debug_mst_cstate[0]}]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports i_i2c_debug_p_gen]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports i_i2c_debug_rd]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports i_i2c_debug_s_gen]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports i_i2c_debug_slave_act]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports {i_i2c_debug_slv_cstate[3]}]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports {i_i2c_debug_slv_cstate[2]}]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports {i_i2c_debug_slv_cstate[1]}]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports {i_i2c_debug_slv_cstate[0]}]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports i_i2c_debug_wr]
set_output_delay -clock PCLK_pclk  1.8  [get_ports i_i2c_ic_activity_intr]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports i_i2c_ic_clk_oe]
set_output_delay -clock i_i2c_ic_clk  1.8  [get_ports i_i2c_ic_data_oe]
set_output_delay -clock PCLK_pclk  3.6  [get_ports i_i2c_ic_en]
set_output_delay -clock PCLK_pclk  1.8  [get_ports i_i2c_ic_gen_call_intr]
set_output_delay -clock PCLK_pclk  1.8  [get_ports i_i2c_ic_rd_req_intr]
set_output_delay -clock PCLK_pclk  1.8  [get_ports i_i2c_ic_rx_done_intr]
set_output_delay -clock PCLK_pclk  1.8  [get_ports i_i2c_ic_rx_full_intr]
set_output_delay -clock PCLK_pclk  1.8  [get_ports i_i2c_ic_rx_over_intr]
set_output_delay -clock PCLK_pclk  1.8  [get_ports i_i2c_ic_rx_under_intr]
set_output_delay -clock PCLK_pclk  1.8  [get_ports i_i2c_ic_start_det_intr]
set_output_delay -clock PCLK_pclk  1.8  [get_ports i_i2c_ic_stop_det_intr]
set_output_delay -clock PCLK_pclk  1.8  [get_ports i_i2c_ic_tx_abrt_intr]
set_output_delay -clock PCLK_pclk  1.8  [get_ports i_i2c_ic_tx_empty_intr]
set_output_delay -clock PCLK_pclk  1.8  [get_ports i_i2c_ic_tx_over_intr]
