// This file was automatically generated by coreAssembler (version J-2015.03-SP1).
// 
// FILENAME : /home/warehouse/shenkaijie/Documents/coreAssembler/design/parkinggate/src/parking.v
// DATE : 11/28/15 20:43:08
// ABSTRACT : Verilog top-level subsystem RTL.
// 

module parking (// Ports for Interface HCLK
                HCLK_hclk,
                // Ports for Interface HRESETn
                HRESETn_hresetn,
                // Ports for Interface PCLK
                PCLK_pclk,
                // Ports for Interface PRESETn
                PRESETn_presetn,
                // Ports for Interface ex_i_ahb_AHB_Master
                ex_i_ahb_AHB_Master_haddr,
                ex_i_ahb_AHB_Master_hburst,
                ex_i_ahb_AHB_Master_hbusreq,
                ex_i_ahb_AHB_Master_hlock,
                ex_i_ahb_AHB_Master_hprot,
                ex_i_ahb_AHB_Master_hsize,
                ex_i_ahb_AHB_Master_htrans,
                ex_i_ahb_AHB_Master_hwdata,
                ex_i_ahb_AHB_Master_hwrite,
                ex_i_ahb_AHB_Master_hgrant,
                ex_i_ahb_AHB_Master_hrdata,
                ex_i_ahb_AHB_Master_hready,
                ex_i_ahb_AHB_Master_hresp,
                // Ports for Interface ex_i_ahb_AHB_Slave
                ex_i_ahb_AHB_Slave_hrdata,
                ex_i_ahb_AHB_Slave_hready_resp,
                ex_i_ahb_AHB_Slave_hresp,
                ex_i_ahb_AHB_Slave_haddr,
                ex_i_ahb_AHB_Slave_hburst,
                ex_i_ahb_AHB_Slave_hmastlock,
                ex_i_ahb_AHB_Slave_hprot,
                ex_i_ahb_AHB_Slave_hready,
                ex_i_ahb_AHB_Slave_hsel,
                ex_i_ahb_AHB_Slave_hsize,
                ex_i_ahb_AHB_Slave_htrans,
                ex_i_ahb_AHB_Slave_hwdata,
                ex_i_ahb_AHB_Slave_hwrite,
                // Ports for Manually exported pins
                i_ahb_pause,
                i_apb_pclk_en,
                i_i2c_ic_clk,
                i_i2c_ic_clk_in_a,
                i_i2c_ic_data_in_a,
                i_i2c_ic_rst_n,
                i_ahb_ahbarbint,
                i_ahb_hmaster_data,
                i_ahb_hrdata_s0,
                i_ahb_hready_resp_s0,
                i_ahb_hresp_s0,
                i_ahb_hsel_s0,
                i_i2c_debug_addr,
                i_i2c_debug_addr_10bit,
                i_i2c_debug_data,
                i_i2c_debug_hs,
                i_i2c_debug_master_act,
                i_i2c_debug_mst_cstate,
                i_i2c_debug_p_gen,
                i_i2c_debug_rd,
                i_i2c_debug_s_gen,
                i_i2c_debug_slave_act,
                i_i2c_debug_slv_cstate,
                i_i2c_debug_wr,
                i_i2c_ic_activity_intr,
                i_i2c_ic_clk_oe,
                i_i2c_ic_data_oe,
                i_i2c_ic_en,
                i_i2c_ic_gen_call_intr,
                i_i2c_ic_rd_req_intr,
                i_i2c_ic_rx_done_intr,
                i_i2c_ic_rx_full_intr,
                i_i2c_ic_rx_over_intr,
                i_i2c_ic_rx_under_intr,
                i_i2c_ic_start_det_intr,
                i_i2c_ic_stop_det_intr,
                i_i2c_ic_tx_abrt_intr,
                i_i2c_ic_tx_empty_intr,
                i_i2c_ic_tx_over_intr
                );

   // Ports for Interface HCLK
   input          HCLK_hclk;
   // Ports for Interface HRESETn
   input          HRESETn_hresetn;
   // Ports for Interface PCLK
   input          PCLK_pclk;
   // Ports for Interface PRESETn
   input          PRESETn_presetn;
   // Ports for Interface ex_i_ahb_AHB_Master
   input  [31:0]  ex_i_ahb_AHB_Master_haddr;
   input  [2:0]   ex_i_ahb_AHB_Master_hburst;
   input          ex_i_ahb_AHB_Master_hbusreq;
   input          ex_i_ahb_AHB_Master_hlock;
   input  [3:0]   ex_i_ahb_AHB_Master_hprot;
   input  [2:0]   ex_i_ahb_AHB_Master_hsize;
   input  [1:0]   ex_i_ahb_AHB_Master_htrans;
   input  [31:0]  ex_i_ahb_AHB_Master_hwdata;
   input          ex_i_ahb_AHB_Master_hwrite;
   output         ex_i_ahb_AHB_Master_hgrant;
   output [31:0]  ex_i_ahb_AHB_Master_hrdata;
   output         ex_i_ahb_AHB_Master_hready;
   output [1:0]   ex_i_ahb_AHB_Master_hresp;
   // Ports for Interface ex_i_ahb_AHB_Slave
   input  [31:0]  ex_i_ahb_AHB_Slave_hrdata;
   input          ex_i_ahb_AHB_Slave_hready_resp;
   input  [1:0]   ex_i_ahb_AHB_Slave_hresp;
   output [31:0]  ex_i_ahb_AHB_Slave_haddr;
   output [2:0]   ex_i_ahb_AHB_Slave_hburst;
   output         ex_i_ahb_AHB_Slave_hmastlock;
   output [3:0]   ex_i_ahb_AHB_Slave_hprot;
   output         ex_i_ahb_AHB_Slave_hready;
   output         ex_i_ahb_AHB_Slave_hsel;
   output [2:0]   ex_i_ahb_AHB_Slave_hsize;
   output [1:0]   ex_i_ahb_AHB_Slave_htrans;
   output [31:0]  ex_i_ahb_AHB_Slave_hwdata;
   output         ex_i_ahb_AHB_Slave_hwrite;
   // Ports for Manually exported pins
   input          i_ahb_pause;
   input          i_apb_pclk_en;
   input          i_i2c_ic_clk;
   input          i_i2c_ic_clk_in_a;
   input          i_i2c_ic_data_in_a;
   input          i_i2c_ic_rst_n;
   output         i_ahb_ahbarbint;
   output [3:0]   i_ahb_hmaster_data;
   output [31:0]  i_ahb_hrdata_s0;
   output         i_ahb_hready_resp_s0;
   output [1:0]   i_ahb_hresp_s0;
   output         i_ahb_hsel_s0;
   output         i_i2c_debug_addr;
   output         i_i2c_debug_addr_10bit;
   output         i_i2c_debug_data;
   output         i_i2c_debug_hs;
   output         i_i2c_debug_master_act;
   output [4:0]   i_i2c_debug_mst_cstate;
   output         i_i2c_debug_p_gen;
   output         i_i2c_debug_rd;
   output         i_i2c_debug_s_gen;
   output         i_i2c_debug_slave_act;
   output [3:0]   i_i2c_debug_slv_cstate;
   output         i_i2c_debug_wr;
   output         i_i2c_ic_activity_intr;
   output         i_i2c_ic_clk_oe;
   output         i_i2c_ic_data_oe;
   output         i_i2c_ic_en;
   output         i_i2c_ic_gen_call_intr;
   output         i_i2c_ic_rd_req_intr;
   output         i_i2c_ic_rx_done_intr;
   output         i_i2c_ic_rx_full_intr;
   output         i_i2c_ic_rx_over_intr;
   output         i_i2c_ic_rx_under_intr;
   output         i_i2c_ic_start_det_intr;
   output         i_i2c_ic_stop_det_intr;
   output         i_i2c_ic_tx_abrt_intr;
   output         i_i2c_ic_tx_empty_intr;
   output         i_i2c_ic_tx_over_intr;

   wire [31:0]  i_ahb_haddr;
   wire [2:0]   i_ahb_hburst;
   wire         i_ahb_hready;
   wire         i_ahb_hsel_s1;
   wire [2:0]   i_ahb_hsize;
   wire [1:0]   i_ahb_htrans;
   wire [31:0]  i_ahb_hwdata;
   wire         i_ahb_hwrite;
   wire [31:0]  i_apb_hrdata;
   wire         i_apb_hready_resp;
   wire [1:0]   i_apb_hresp;
   wire [31:0]  i_apb_paddr;
   wire         i_apb_penable;
   wire         i_apb_psel_s0;
   wire [15:0]  i_apb_pwdata;
   wire         i_apb_pwrite;
   wire [15:0]  i_i2c_prdata;

   i_ahb_DW_ahb i_ahb
      (.hclk           (HCLK_hclk),
       .hresetn        (HRESETn_hresetn),
       .pause          (i_ahb_pause),
       .haddr_m1       (ex_i_ahb_AHB_Master_haddr),
       .hburst_m1      (ex_i_ahb_AHB_Master_hburst),
       .hbusreq_m1     (ex_i_ahb_AHB_Master_hbusreq),
       .hlock_m1       (ex_i_ahb_AHB_Master_hlock),
       .hprot_m1       (ex_i_ahb_AHB_Master_hprot),
       .hsize_m1       (ex_i_ahb_AHB_Master_hsize),
       .htrans_m1      (ex_i_ahb_AHB_Master_htrans),
       .hwdata_m1      (ex_i_ahb_AHB_Master_hwdata),
       .hwrite_m1      (ex_i_ahb_AHB_Master_hwrite),
       .hgrant_m1      (ex_i_ahb_AHB_Master_hgrant),
       .hsel_s0        (i_ahb_hsel_s0),
       .hready_resp_s0 (i_ahb_hready_resp_s0),
       .hresp_s0       (i_ahb_hresp_s0),
       .hrdata_s0      (i_ahb_hrdata_s0),
       .hsel_s1        (i_ahb_hsel_s1),
       .hready_resp_s1 (i_apb_hready_resp),
       .hresp_s1       (i_apb_hresp),
       .hrdata_s1      (i_apb_hrdata),
       .hsel_s2        (ex_i_ahb_AHB_Slave_hsel),
       .hready_resp_s2 (ex_i_ahb_AHB_Slave_hready_resp),
       .hresp_s2       (ex_i_ahb_AHB_Slave_hresp),
       .hrdata_s2      (ex_i_ahb_AHB_Slave_hrdata),
       .haddr          (i_ahb_haddr),
       .hburst         (i_ahb_hburst),
       .hprot          (ex_i_ahb_AHB_Slave_hprot),
       .hsize          (i_ahb_hsize),
       .htrans         (i_ahb_htrans),
       .hwdata         (i_ahb_hwdata),
       .hwrite         (i_ahb_hwrite),
       .hready         (i_ahb_hready),
       .hresp          (ex_i_ahb_AHB_Master_hresp),
       .hrdata         (ex_i_ahb_AHB_Master_hrdata),
       .ahbarbint      (i_ahb_ahbarbint),
       .hmaster        (),
       .hmaster_data   (i_ahb_hmaster_data),
       .hmastlock      (ex_i_ahb_AHB_Slave_hmastlock));

   i_apb_DW_apb i_apb
      (.hclk        (HCLK_hclk),
       .hresetn     (HRESETn_hresetn),
       .haddr       (i_ahb_haddr),
       .hready      (i_ahb_hready),
       .hsel        (i_ahb_hsel_s1),
       .htrans      (i_ahb_htrans),
       .hwrite      (i_ahb_hwrite),
       .hsize       (i_ahb_hsize),
       .hburst      (i_ahb_hburst),
       .hresp       (i_apb_hresp),
       .hready_resp (i_apb_hready_resp),
       .hwdata      (i_ahb_hwdata),
       .hrdata      (i_apb_hrdata),
       .pclk_en     (i_apb_pclk_en),
       .paddr       (i_apb_paddr),
       .penable     (i_apb_penable),
       .pwrite      (i_apb_pwrite),
       .pwdata      (i_apb_pwdata),
       .psel_s0     (i_apb_psel_s0),
       .prdata_s0   (i_i2c_prdata));

   i_i2c_DW_apb_i2c i_i2c
      (.ic_start_det_intr (i_i2c_ic_start_det_intr),
       .ic_stop_det_intr  (i_i2c_ic_stop_det_intr),
       .ic_activity_intr  (i_i2c_ic_activity_intr),
       .ic_rx_done_intr   (i_i2c_ic_rx_done_intr),
       .ic_tx_abrt_intr   (i_i2c_ic_tx_abrt_intr),
       .ic_rd_req_intr    (i_i2c_ic_rd_req_intr),
       .ic_tx_empty_intr  (i_i2c_ic_tx_empty_intr),
       .ic_tx_over_intr   (i_i2c_ic_tx_over_intr),
       .ic_rx_full_intr   (i_i2c_ic_rx_full_intr),
       .ic_rx_over_intr   (i_i2c_ic_rx_over_intr),
       .ic_rx_under_intr  (i_i2c_ic_rx_under_intr),
       .ic_gen_call_intr  (i_i2c_ic_gen_call_intr),
       .pclk              (PCLK_pclk),
       .presetn           (PRESETn_presetn),
       .psel              (i_apb_psel_s0),
       .penable           (i_apb_penable),
       .pwrite            (i_apb_pwrite),
       .paddr             (i_apb_paddr[7:0]),
       .pwdata            (i_apb_pwdata),
       .prdata            (i_i2c_prdata),
       .ic_clk            (i_i2c_ic_clk),
       .ic_clk_in_a       (i_i2c_ic_clk_in_a),
       .ic_data_in_a      (i_i2c_ic_data_in_a),
       .ic_rst_n          (i_i2c_ic_rst_n),
       .debug_s_gen       (i_i2c_debug_s_gen),
       .debug_p_gen       (i_i2c_debug_p_gen),
       .debug_data        (i_i2c_debug_data),
       .debug_addr        (i_i2c_debug_addr),
       .debug_rd          (i_i2c_debug_rd),
       .debug_wr          (i_i2c_debug_wr),
       .debug_hs          (i_i2c_debug_hs),
       .debug_master_act  (i_i2c_debug_master_act),
       .debug_slave_act   (i_i2c_debug_slave_act),
       .debug_addr_10bit  (i_i2c_debug_addr_10bit),
       .debug_mst_cstate  (i_i2c_debug_mst_cstate),
       .debug_slv_cstate  (i_i2c_debug_slv_cstate),
       .ic_clk_oe         (i_i2c_ic_clk_oe),
       .ic_data_oe        (i_i2c_ic_data_oe),
       .ic_en             (i_i2c_ic_en));

   assign ex_i_ahb_AHB_Master_hready = i_ahb_hready;
   assign ex_i_ahb_AHB_Slave_haddr = i_ahb_haddr;
   assign ex_i_ahb_AHB_Slave_hburst = i_ahb_hburst;
   assign ex_i_ahb_AHB_Slave_hready = i_ahb_hready;
   assign ex_i_ahb_AHB_Slave_hsize = i_ahb_hsize;
   assign ex_i_ahb_AHB_Slave_htrans = i_ahb_htrans;
   assign ex_i_ahb_AHB_Slave_hwdata = i_ahb_hwdata;
   assign ex_i_ahb_AHB_Slave_hwrite = i_ahb_hwrite;

   // Note: i_apb_paddr[31:8] is open

endmodule
