# Set attributes defining registered ports.

set_attribute -quiet -type boolean [find port {HCLK_hclk}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {HRESETn_hresetn}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {PCLK_pclk}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {PRESETn_presetn}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[31]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[30]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[29]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[28]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[27]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[26]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[25]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[24]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[23]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[22]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[21]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[20]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[19]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[18]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[17]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[16]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[15]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[14]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[13]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[12]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[11]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[10]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[9]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[8]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[7]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[6]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[5]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[4]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_haddr[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hburst[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hburst[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hburst[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hbusreq}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hlock}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hprot[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hprot[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hprot[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hprot[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hsize[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hsize[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hsize[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_htrans[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_htrans[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[31]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[30]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[29]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[28]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[27]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[26]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[25]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[24]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[23]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[22]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[21]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[20]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[19]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[18]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[17]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[16]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[15]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[14]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[13]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[12]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[11]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[10]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[9]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[8]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[7]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[6]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[5]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[4]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwdata[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hwrite}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[31]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[30]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[29]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[28]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[27]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[26]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[25]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[24]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[23]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[22]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[21]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[20]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[19]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[18]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[17]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[16]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[15]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[14]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[13]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[12]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[11]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[10]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[9]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[8]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[7]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[6]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[5]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[4]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[3]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[2]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hrdata[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hready_resp}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hresp[1]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hresp[0]}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {i_ahb_pause}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {i_apb_pclk_en}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {i_i2c_ic_clk}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_clk_in_a}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {i_i2c_ic_data_in_a}] rtIsRegisteredInput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_rst_n}] rtIsRegisteredInput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hgrant}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[31]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[30]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[29]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[28]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[27]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[26]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[25]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[24]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[23]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[22]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[21]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[20]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[19]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[18]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[17]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[16]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[15]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[14]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[13]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[12]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[11]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[10]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[9]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[8]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[7]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[6]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[5]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[4]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[3]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hrdata[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hready}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hresp[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Master_hresp[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[31]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[30]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[29]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[28]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[27]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[26]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[25]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[24]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[23]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[22]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[21]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[20]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[19]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[18]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[17]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[16]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[15]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[14]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[13]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[12]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[11]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[10]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[9]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[8]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[7]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[6]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[5]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[4]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[3]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_haddr[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hburst[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hburst[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hburst[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hmastlock}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hprot[3]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hprot[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hprot[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hprot[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hready}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hsel}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hsize[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hsize[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hsize[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_htrans[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_htrans[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[31]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[30]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[29]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[28]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[27]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[26]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[25]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[24]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[23]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[22]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[21]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[20]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[19]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[18]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[17]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[16]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[15]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[14]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[13]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[12]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[11]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[10]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[9]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[8]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[7]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[6]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[5]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[4]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[3]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwdata[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {ex_i_ahb_AHB_Slave_hwrite}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_ahbarbint}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hmaster_data[3]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hmaster_data[2]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hmaster_data[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hmaster_data[0]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[31]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[30]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[29]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[28]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[27]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[26]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[25]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[24]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[23]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[22]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[21]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[20]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[19]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[18]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[17]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[16]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[15]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[14]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[13]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[12]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[11]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[10]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[9]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[8]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[7]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[6]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[5]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[4]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[3]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hrdata_s0[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hready_resp_s0}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hresp_s0[1]}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_ahb_hresp_s0[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_ahb_hsel_s0}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_i2c_debug_addr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_addr_10bit}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_data}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_hs}] rtIsRegisteredOutput false
set_attribute -quiet -type boolean [find port {i_i2c_debug_master_act}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_mst_cstate[4]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_mst_cstate[3]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_mst_cstate[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_mst_cstate[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_mst_cstate[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_p_gen}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_rd}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_s_gen}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_slave_act}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_slv_cstate[3]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_slv_cstate[2]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_slv_cstate[1]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_slv_cstate[0]}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_debug_wr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_activity_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_clk_oe}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_data_oe}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_en}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_gen_call_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_rd_req_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_rx_done_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_rx_full_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_rx_over_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_rx_under_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_start_det_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_stop_det_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_tx_abrt_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_tx_empty_intr}] rtIsRegisteredOutput true
set_attribute -quiet -type boolean [find port {i_i2c_ic_tx_over_intr}] rtIsRegisteredOutput true
